import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
print("MEIKO MEIKO KAITO KAITO KAGAMINE RINNN KAGAMINE RREEN MEGURIME RUKA HATSUNE MIKUUUU")
w = pd.read_csv('Weather Dataset - Trial Activity DataSet.csv')
w.info()
sb.barplot(w['wind_speed'])
plt.show()
sb.distplot(w['temperature'])
plt.show()
sb.distplot(w['humidity'])
plt.show()
sb.jointplot(w['temperature'])
plt.show()
sb.jointplot(w['temperature'],kind = 'hex')
plt.show()
sb.jointplot(w['temperature'],kind = 'kde')
plt.show()
sb.pairplot(w[['humidity', 'temperature', 'air_pollution_index']])
plt.show()
sb.stripplot(w['weather_type'])
plt.show()
sb.swarmplot(w['humidity'])
plt.show()
sb.boxplot(w['humidity'])
plt.show()
sb.barplot(w['humidity'])
plt.show()
sb.countplot(w['weather_type'])
plt.show()
sb.pointplot(w['humidity'])
plt.show()
sb.lmplot(x="humidity", y="temperature", data=w)
plt.show()
sb.lmplot(x="humidity", y="temperature",hue = 'weather_type', data=w)
plt.show()
