import time
print('AND NOW, ITS TIME!!')
time.sleep(2)
print('FOR THE MOMENT YOUVE BEEN WAITING FOR!!!')
time.sleep(3)
print('1...')
time.sleep(1)
print('2...')
time.sleep(1)
print('3...')
time.sleep(1)
redy = input('READY? ')
print('MIKUMIKU BEEEEEEEEEEEEEEEEEEEEEAAAAAAAAAAAAAAAAAMMM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
time.sleep(5)
print('KEEP GOING!!!!!!!!!!!')