import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
print("e")
w = pd.read_csv('penguins.csv')
w.info()
sb.barplot(w['body_mass_g'])
plt.show()
sb.distplot(w['body_mass_g'])
plt.show()
sb.distplot(w['bill_length_mm'])
plt.show()
sb.jointplot(w['body_mass_g'])
plt.show()
sb.jointplot(w['body_mass_g'],kind = 'hex')
plt.show()
sb.jointplot(w['body_mass_g'],kind = 'kde')
plt.show()
sb.pairplot(w[['bill_length_mm', 'body_mass_g', 'flipper_length_mm']])
plt.show()
sb.stripplot(w['flipper_length_mm'])
plt.show()
sb.swarmplot(w['bill_length_mm'])
plt.show()
sb.boxplot(w['bill_length_mm'])
plt.show()
sb.barplot(w['bill_length_mm'])
plt.show()
sb.countplot(w['flipper_length_mm'])
plt.show()
sb.pointplot(w['bill_length_mm'])
plt.show()
sb.lmplot(x="bill_length_mm", y="body_mass_g", data=w)
plt.show()
sb.lmplot(x="bill_length_mm", y="body_mass_g",hue = 'flipper_length_mm', data=w)
plt.show()
